accounts/urls.py
from django.urls import path
from . import views

from .views import SignUpView, EditUserView, EditProfileView, ViewProfileView, ChangePasswordView, password_success

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<str:username>/edit_user/', EditUserView.as_view(), name='edit_user'),
    path('password/', ChangePasswordView.as_view(), name='change-password'),
    path('password_success/', views.password_success, name='password_success'),
    path('<str:username>/view_profile/', ViewProfileView.as_view(), name='view_profile'),
    path('<str:username>/edit_profile/', EditProfileView.as_view(), name='edit_profile')
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # For User Creation
    path('accounts/', include('django.contrib.auth.urls')), # For User Login/Logout
    path('projects/', include("projects.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='all'),
    path('<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<int:pk>/comment', views.CommentCreateView.as_view(), name='project_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('projects')), name='project_comment_delete'),
    path('project_create', views.ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/update', views.ProjectUpdateView.as_view(), name='project_update'),
    path('<int:pk>/delete', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/like', views.ProjectLikeView, name='project_like'),
    # path('jarvis')
]


# I use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

personal_portfolio/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <link rel='stylesheet' href="{% static 'css/base.css' %}">
  <link rel='stylesheet' href="https://fonts.googleapis.com/css?family=Barlow|Poppins">
  <script src="https://kit.fontawesome.com/9c98221fc8.js" crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<nav class="navbar navbar-expand-lg">
    <div class="container justify-content-end">
      <!-- <a class="navbar-brand" href="{% url 'home' %}">Zane's Portfolio Site</a> -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"><i class="fas fa-bars"></i></span>
        </button>
        <div class="collapse navbar-collapse justify-content-end" id="navbarTogglerDemo02">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Projects</a> 
              <ul class="dropdown-menu text-white bg-dark" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'projects:all' %}">View Projects</a>
                <a class="dropdown-item" href="{% url 'projects:project_create' %}">Create Project</a>
              </ul>
            </li>
            <li class="nav-item dropdown">
            {% if user.is_authenticated %}
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a> 
              <ul class="dropdown-menu bg-dark text-white" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'accounts:view_profile' user.username %}">View Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:edit_user' user.username %}">Edit User</a>
                <a class="dropdown-item" href="{% url 'accounts:edit_profile' user.username %}">Edit Profile</a>
                <a class="dropdown-item" href="{% url 'accounts:change-password' %}">Change Password</a>
                <a class="dropdown-item" href="{% url 'logout' %}">Log Out</a>
            {% else %}
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Profile</a> 
              <ul class="dropdown-menu text-white bg-dark" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'login' %}">Log In</a>
                <a class="dropdown-item" href="{% url 'accounts:signup' %}">Sign Up</a>
            {% endif %}
            {% if user.is_superuser %}
              <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
            {% endif %}
              </ul>
            </li>
          </ul>
        </div>
    </div>

</nav>

<div class="container" id="body_container">
    {% block page_content %}{% endblock %}
</div>

<footer class="footer mt-auto text-center text-white text-muted">

  {% if not user.is_authenticated %}
    {% if 'login' not in request.path %}
      <a type="button" class="btn" href="{% url 'login' %}" id="footer_link">Log In</a>
      <a type="button" class="btn" href="{% url 'accounts:signup' %}" id="footer_link">Sign Up</a>
      <br>
    {% endif %}
  {% endif %}
  <p><small>by Zane Wilson, for Zane Wilson</small></p>

  <!-- Social Media Widgets -->
  <div class="wrapper">
      <a href="https://www.facebook.com/zaneohh/" target="_blank">
          <div class="icon facebook">
          <i class="fab fa-facebook-f"></i>
          </div>  
      </a>
      <a href="https://twitter.com/zane_ohh" target="_blank">
          <div class="icon twitter">
          <i class="fab fa-twitter"></i>
          </div>
      </a>
      <a href="https://www.instagram.com/zane_ohh/" target="_blank">
          <div class="icon instagram">
          <i class="fab fa-instagram"></i>
          </div>
      </a>
      <a href="https://github.com/zaneaw" target="_blank">
          <div class="icon github">
          <i class="fab fa-github"></i>
          </div>
      </a>
      <a href="https://www.linkedin.com/in/zaneaw/" target="_blank">
          <div class="icon linkedin">
          <i class="fab fa-linkedin"></i>
          </div>
      </a>
  </div>
  <br>
  <span><small>Back to <a href="#" id="pink_link">top</a>
    <br>
    &copy; 2021 Zane Wilson</small></span>
</footer>
</html>