accounts/urls.py
from django.urls import path
from . import views

from .views import SignUpView, EditUserView, EditProfileView, ViewProfileView, ChangePasswordView, password_success

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('<str:username>/edit_user/', EditUserView.as_view(), name='edit_user'),
    path('password/', ChangePasswordView.as_view(), name='change-password'),
    path('password_success/', views.password_success, name='password_success'),
    path('<str:username>/view_profile/', ViewProfileView.as_view(), name='view_profile'),
    path('<str:username>/edit_profile/', EditProfileView.as_view(), name='edit_profile')
]

home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import debug_toolbar

urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')), # For User Creation
    path('accounts/', include('django.contrib.auth.urls')), # For User Login/Logout
    path('projects/', include("projects.urls")),
    path('__debug__/', include(debug_toolbar.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='projects'

urlpatterns = [
    path('', views.ProjectListView.as_view(), name='all'),
    path('<int:pk>/', views.ProjectDetailView.as_view(), name='project_detail'),
    path('<int:pk>/comment', views.CommentCreateView.as_view(), name='project_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('projects')), name='project_comment_delete'),
    path('project_create', views.ProjectCreateView.as_view(), name='project_create'),
    path('<int:pk>/update', views.ProjectUpdateView.as_view(), name='project_update'),
    path('<int:pk>/delete', views.ProjectDeleteView.as_view(), name='project_delete'),
    path('<int:pk>/like', views.ProjectLikeView, name='project_like'),
    # path('jarvis')
]


# I use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

projects/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import MinLengthValidator, MaxLengthValidator
from django.conf import settings
from django.urls import reverse
from ckeditor.fields import RichTextField


def file_size(value):
    limit = 2621440 # 2.5 * 1024 * 1024, or 2.5MB
    if value.size > limit:
        raise ValidationError('File size is too large. Size should not exceed 2.5MB')


class Project(models.Model):
    title = models.CharField(max_length=30, validators=[MinLengthValidator(2, "Must be more than 2 characters."), MaxLengthValidator(30, "Must be less than 30 characters.")])
    desc = RichTextField(blank=True, null=True)
    repo = models.URLField(blank=True)
    image = models.ImageField(null=True, blank=True, validators=[file_size], upload_to="media/")
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    likes = models.ManyToManyField(User, related_name='liked_projects')


    def total_likes(self):
        return self.likes.count()
        
    # This is what shows up in the admin list
    def __str__(self):
        return f"{self.title} - {self.owner}"


class Comment(models.Model):
    project = models.ForeignKey(Project, related_name='comments', on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    text = models.TextField(validators=[MinLengthValidator(3, "Comments must be more than 2 characters")])
    date_added = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return self.text + '...'

projects/forms.py
from django import forms

from .models import Project


class ProjectCreateForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ("title", "desc", "repo", "image")
        labels = {
            "title": "Title",
            "desc": "Description",
            "repo": "Repository Link",
            "image": "Image",
            "owner": "Created by",
        }
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control", "placeholder": "Example Title"}),
            "desc": forms.Textarea(attrs={"class": "form-control", "placeholder": "Describe your project."}),
            "repo": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "https://github.com/user-name/repository-name"}
            ),  # Go back to - https://youtu.be/6-XXvUENY_8?t=738
            "owner": forms.TextInput(attrs={"class": "form-control"}),
        }

    def send_email(self):
        # send email using the self.cleaned_data dictionary
        pass


class ProjectUpdateForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["title", "desc", "repo", "image"]
        labels = {
            "title": "Title",
            "desc": "Description",
            "repo": "Repository Link",
            "image": "Image",
            "owner": "Created by",
        }
        widgets = {
            "title": forms.TextInput(attrs={"class": "form-control"}),
            "desc": forms.Textarea(attrs={"class": "form-control"}),
            "repo": forms.TextInput(attrs={"class": "form-control"}),
            "owner": forms.TextInput(attrs={"class": "form-control"}),
        }


class CommentForm(forms.Form):
    comment = forms.CharField(
        required=True, max_length=500, min_length=3, strip=True)




# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

projects/views.py
from django.http.response import HttpResponse, HttpResponseRedirect
from django.views.generic.edit import UpdateView, FormView
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse, reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.http import FileResponse
import os

from projects.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from projects.forms import ProjectCreateForm, ProjectUpdateForm, CommentForm
from projects.models import Project, Comment


class ProjectListView(OwnerListView):
    model = Project
    template_name = 'projects/project_list.html'


class ProjectDetailView(OwnerDetailView):
    model = Project
    template_name = 'projects/project_detail.html'

    def get(self, request, pk):
        p = Project.objects.get(id=pk)
        comments = Comment.objects.filter(project=p).order_by('-date_updated')
        comment_form = CommentForm()
        total_likes = p.total_likes()
        liked = False
        if p.likes.filter(id=self.request.user.id).exists():
            liked = True
        ctx = {'project': p, 'total_likes': total_likes, 'liked': liked, 'comment_form': comment_form, 'comments': comments}
        return render(request, self.template_name, ctx)


class ProjectCreateView(LoginRequiredMixin, FormView):
    model = Project
    form_class = ProjectCreateForm
    template_name = 'projects/project_create.html'
    success_url = reverse_lazy('projects:all')
    
    def form_valid(self, form):
        # This method is called when valid form data has been POSTed
        # It should return an HttpResponse
        form.send_email()
        return super().form_valid(form)

    def post(self, request, pk=None):
        form = ProjectCreateForm(request.POST, request.FILES or None)
        ctx = {'form': form}
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to model before save
        project = form.save(commit=False)
        project.owner = self.request.user
        project.save()
        return redirect('projects:project_detail', project.pk)


class ProjectUpdateView(LoginRequiredMixin, UpdateView):
    model = Project
    form_class = ProjectUpdateForm
    template_name = 'projects/project_update.html'
    
    def get(self, request, pk):
        project_inst = get_object_or_404(Project, id=pk, owner=self.request.user)
        form = ProjectCreateForm(instance=project_inst)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk = None, *args, **kwargs):
        self.object = self.get_object() # assign the object to the
        project_inst = get_object_or_404(Project, id=pk, owner=self.request.user)
        form = ProjectCreateForm(request.POST, request.FILES or None, instance=project_inst)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        project = form.save(commit=False)
        project.save()

        return redirect('projects:project_detail', self.object.pk)

    def form_valid(self, form):
        return redirect('projects:project_detail', self.object.pk)


class ProjectDeleteView(OwnerDeleteView):
    model = Project
    template_name = 'projects/project_delete.html'
    success_url = reverse_lazy('projects:all')


def ProjectLikeView(request, pk):
    project = get_object_or_404(Project, id=request.POST.get('project_pk'))
    liked = False # Default value
    if project.likes.filter(id=request.user.id).exists():
        project.likes.remove(request.user)
        liked = False
    else:
        project.likes.add(request.user)
        liked = True
    return HttpResponseRedirect(reverse('projects:project_detail', args=[str(pk)]))
    # 'request' contains the users ID if logged in when clicking 'like'.
    # project.likes.filter(id=request.user.id) then looks at the current 
    # project's likes and filters them to show if the current user id has 
    # liked the current project. If it exists, it 'removes' the like. If 
    # it doesn't, it adds the like to the DB\
    # This code then is passed into the ProjectDetailView


class CommentCreateView(LoginRequiredMixin, View):
    model = Comment
    template_name = 'projects/project_comment_create.html'

    def post(self, request, pk):
        p = get_object_or_404(Project, id=pk)
        comment = Comment(
            text=request.POST['comment'], owner=request.user, project=p)
        comment.save()
        return redirect(reverse('projects:project_detail', args=[pk]))


class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = 'projects/project_comment_delete.html'

    def get_success_url(self):
        project = self.object.project
        return reverse('projects:project_detail', args=[project.id])

projects/templates/projects/jarvis.html
{% extends "base.html" %}
{% load jarvis_script %}
{% load static %}
{% block page_content %}
 <head>
     <title>Jarvis by Zane</title>
 </head>

 <body class="text-white bk-dark">


 </body>

projects/templates/projects/project_comment_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page_content %}

<head>
  <title>Delete Comment</title>
</head>

<body class="text-center text-white bg-dark">
  <main class="px-3">

    <h2>Delete Comment...</h2>
    <p>Are you <strong>sure</strong>?</p>
    <p>{{ comment.text }}</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input type="submit" class="btn btn-secondary" value="Delete">
      <a href="{% url 'projects:project_detail' comment.project.id %}" class="btn btn-primary">Cancel</a>
    </form>
  </main>
</body>
{% endblock %}

projects/templates/projects/project_confirm_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block page_content %}
<title>Delete Project?</title>
<h2>Delete Project</h2>

<p>Are you sure you want to delete the project: {{ project.title }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  {{ form|crispy }}
  <input type="submit" value="Delete">
  <input type="button" value="Go back" onclick="history.back()">
</form>
{% endblock %}

projects/templates/projects/project_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_content %}

<head>
  <title>Create Project</title>
  <link rel='stylesheet' href="{% static 'css/project_create.css' %}">
</head>

<body class="text-white bg-dark">
  <h2>Create your Project</h2>
  <div class="form-group">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}
      {{ form|crispy }}
      <br>
      <input type="submit" value="Submit" class="btn btn-primary">
      <input type="submit" value="Cancel" class="btn btn-secondary" onclick="window.location.href='{% url 'projects:all' %}';return false;">
    </form>
  </div>
</body>
{% endblock %}

projects/templates/projects/project_delete.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block page_content %}
<head>
  <title>Delete Project?</title>
  <link rel='stylesheet' href="{% static 'css/project_delete.css' %}">
</head>

<body class="text-center text-white bg-dark">
  <main class="px-3">
    <h2>Delete Project</h2>

    <p>Are you <strong>SURE</strong> you want to <strong>DELETE</strong> your project: {{ project.title }}?</p>

    <form action="" method="POST">
      {% csrf_token %}
      <input class='btn btn-secondary' type="submit" value="Delete">
      <input class='btn btn-secondary' type="button" value="Go back" onclick="history.back()">
    </form>
    <small class="text-muted">This action cannot be undone.</small>
  </main>
</body>
{% endblock %}

projects/templates/projects/project_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% load humanize %}
{% block page_content %}

<head>
    <link rel='stylesheet' href="{% static 'css/project_detail.css' %}">
</head>

<body class="text-white bg-dark">
    {% if project.title %}
        <title>{{ project.title }}</title>
        <h2>{{ project.title }}</h2>
    {% else %}
        <title>Project Details</title>
        <h2>Project Details</h2>
    {% endif %}

    <div><i><small>Posted by: {{ project.owner.username }} | 
        <a id="pink_link_2" href="{% url 'accounts:view_profile' project.owner.username %}">View Profile</a><br></small></i>
    </div>
    <!-- Social Media Links -->
    <div class="wrapper">
        {% if project.owner.profile.facebook_url %}
            <a href="{{ project.owner.profile.facebook_url }}" target="_blank">
                <div class="icon facebook">
                <div class="tooltip">Facebook</div>
                <i class="fab fa-facebook-f"></i>
                </div>  
            </a>
        {% endif %}
        {% if project.owner.profile.twitter_url %}
            <a href="{{ project.owner.profile.twitter_url }}" target="_blank">
                <div class="icon twitter">
                <div class="tooltip">Twitter</div>
                <i class="fab fa-twitter"></i>
                </div>
            </a>
        {% endif %}
        {% if project.owner.profile.instagram_url %}
            <a href="{{ project.owner.profile.instagram_url }}" target="_blank">
                <div class="icon instagram">
                <div class="tooltip">Instagram</div>
                <i class="fab fa-instagram"></i>
                </div>
            </a>
        {% endif %}
        {% if project.owner.profile.github_url %}
            <a href="{{ project.owner.profile.github_url }}" target="_blank">
                <div class="icon github">
                <div class="tooltip">Github</div>
                <i class="fab fa-github"></i>
                </div>
            </a>
        {% endif %}
        {% if project.owner.profile.linkedin_url %}
            <a href="{{ project.owner.profile.linkedin_url }}" target="_blank">
                <div class="icon linkedin">
                <div class="tooltip">Linkedin</div>
                <i class="fab fa-linkedin"></i>
                </div>
            </a>
        {% endif %}
    </div>

<form action="{% url 'projects:project_like' project.pk %}" method="POST" id="like_unlike">
    {% if user.is_authenticated %}
        {% csrf_token %}
        {% if liked %}<i class="text-muted">(liked)</i>{% endif %}
        <i class="text-muted">({{ total_likes }}
        {% if total_likes == 1 %} Like{% else %} Likes{% endif %})</i>
        {% if not liked %}
            <button type="submit" name="project_pk" value="{{ project.pk }}" class="btn btn-link"><i id="action2" class="fas fa-thumbs-up" style="color: dodgerblue;"></i></button>
        {% else %}
            <button type="submit" name="project_pk" value="{{ project.pk }}" class="btn btn-link"><i id="action2" class="fas fa-thumbs-down" style="color: Tomato;"></i></button>
        {% endif %}
    {% else %}
        <span>Please <strong><a href="{% url 'login' %}" id="pink_link_2">LOG IN</a></strong> to be able to like projects!</span>
        <br>
        <button type="button" class="btn btn-link"><i class="fas fa-thumbs-up" style="color: dodgerblue;"></i></button>- {{ total_likes }} 
        {% if total_likes == 1 %} Like {% else %} Likes {% endif %}
    {% endif %}
</form>


    <hr>

    <p>
    {{ project.desc|safe }}
    </p>

    <br>

    {% if project.repo %}
        <a href="{{ project.repo }}" target="_blank" id="pink_link_2">View Project Source Code</a>
    {% else %}
        <p>No repository link.</p>
    {% endif %}

    <br>

    {% if project.owner == user %}
        <br>
        <p>
            <a id="action_edit" href="{% url 'projects:project_update' project.pk %}">Edit <i id="action2" class="fa fa-pencil"></i></a> | 
            <a id="action_delete" href="{% url 'projects:project_delete' project.pk %}?next={% url 'projects:all' %}">Delete <i id="action2" class="fa fa-trash"></i></a>
        </p>
        <br>
    {% endif %}
    <hr>

    {% if user.is_authenticated %}
        <form method="POST" action="{% url 'projects:project_comment_create' project.id%}">
            {% csrf_token %}
            {{ comment_form|crispy }} <input type="submit" value="Add Comment" class="btn btn-secondary btn-sm">
        </form>
    {% endif %}
    {% for comment in comments %}
    <p>
        <i><small><a id="pink_link_2" href="{% url 'accounts:view_profile' comment.owner %}">@{{ comment.owner }}</a> said:</small></i>  <br>  {{ comment.text }} <i><br><small>({{ comment.date_updated|naturaltime}})</i></small>
        {% if user == comment.owner %}
        <a href="{% url 'projects:project_comment_delete' comment.id %}"><i id="action2" class="fa fa-trash"></i></a>

        {% endif %}
    </p>
    {% endfor %}

    <hr>

    <a class="btn btn-primary" href="{% url 'projects:all' %}">Back to all projects</a>
</body>
{% endblock %}

projects/templates/projects/project_list.html
{% extends "base.html" %}
{% load static %}
{% block page_content %}

<head>
    <title>Projects List</title>
    <link rel="stylesheet" href="{% static 'css/project_list.css' %}">

</head>

<body class="text-white bg-dark">
    <section class="py-4 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">Projects</h1>
                <p class="lead text-muted">Below are some of my favorite projects that you can check out. You can like
                    and comment on ones you find interesting. Feel free to post some of your own projects as well!
                    <br>Enjoy!</p>
                <p>
                    <a href="{% url 'projects:project_create' %}" class="btn btn-primary my-2">Post a Project</a>
                    <a href="https://zaneportfolio.s3.us-east-2.amazonaws.com/media/resume_website.pdf" class="btn btn-secondary my-2" target="_blank">Zane's Resume</a>
                </p>
            </div>
        </div>
    </section>

    <div class="album py-5">
        <div class="container">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% if project_list %}
                {% for project in project_list %}
                <div class="col">
                    <div class="card">
                        {% if project.image %}
                        <a href="{% url 'projects:project_detail' project.pk %}"><img class="img-fluid rounded" src="{{ project.image.url }}"></a>
                        {% else %}
                        <a href="{% url 'projects:project_detail' project.pk %}"><img class="img-fluid rounded"
                            src="{% static 'personal_portfolio/images/filler_project_image.jpg' %}"></a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ project.title }}</h5>
                            <p class="card-text">{{ project.desc|truncatewords:15|safe }} <br><br><small
                                    class="text-muted">Posted by: {{ project.owner }}</small></p>
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="{% url 'projects:project_detail' project.pk %}" class="btn btn-secondary"
                                    type="button" id="read_more">View</a>
                                <div class="btn-group">
                                    {% if project.owner == user %}
                                    <a type="button" class="btn btn-link btn-sm"
                                        href="{% url 'projects:project_update' project.pk %}"><i id="action2"
                                            class="fa fa-pencil"></i></a>
                                    <a type="button" class="btn btn-link btn-sm"
                                        href="{% url 'projects:project_delete' project.pk %}"><i id="action2"
                                            class="fa fa-trash"></i></a>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
                {% else %}
                <p>There are no projects to display... Maybe try adding some!</p>
                {% endif %}
            </div>
        </div>
    </div>
</body>
{% endblock %}

projects/templates/projects/project_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_content %}

<head>
  <title>Update Project</title>
  <link rel="stylesheet" href="{% static 'css/project_update.css' %}">
</head>

<body class="text-white bg-dark">
  <h2>Update your Project</h2>
  <div class="form-group">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form.media }}
      {{ form|crispy }}
      <br>
      <input type="submit" value="Submit" class="btn btn-primary">
      <input type="submit" value="Cancel" class="btn btn-secondary" onclick="window.location.href='{% url 'projects:all' %}';return false;">
    </form>
  </div>
</body>
{% endblock %}